AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  AssetBucket:
    Type: String
  APIStageName:
    Type: String
    Default: Test
Resources:
  SampleApi:
    Type: AWS::Serverless::Api
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-SampleAPI
      StageName:
        Ref: APIStageName
      TracingEnabled: true
      Auth:
        DefaultAuthorizer: AWS_IAM
        InvokeRole: NONE
      MethodSettings:
      - HttpMethod: '*'
        LoggingLevel: INFO
        ResourcePath: /*
        MetricsEnabled: true
        DataTraceEnabled: true
      AccessLogSetting:
        DestinationArn:
          Fn::Sub: ${SampleApiLogGroup.Arn}
        Format: '{ ''requestId'':''$context.requestId'', ''ip'': ''$context.identity.sourceIp'',
          ''caller'':''$context.identity.caller'', ''user'':''$context.identity.user'',''requestTime'':''$context.requestTime'',
          ''xrayTraceId'':''$context.xrayTraceId'', ''wafResponseCode'':''$context.wafResponseCode'',
          ''httpMethod'':''$context.httpMethod'',''resourcePath'':''$context.resourcePath'',
          ''status'':''$context.status'',''protocol'':''$context.protocol'', ''responseLength'':''$context.responseLength''
          }'
    Metadata:
      SamResourceId: SampleApi
  SampleApiLogGroup:
    Type: AWS::Logs::LogGroup
    DependsOn: SampleApi
    DeletionPolicy: Delete
    Properties:
      LogGroupName:
        Fn::Sub: /aws/apigateway/${SampleApi}
      RetentionInDays: 1
    Metadata:
      SamResourceId: SampleApiLogGroup
  SampleAthenaSpillBucket:
    Type: AWS::S3::Bucket
    Metadata:
      SamResourceId: SampleAthenaSpillBucket
  SampleConnector:
    Type: AWS::Serverless::Connector
    Properties:
      Source:
        Id: SampleInlineFunction
      Destination:
        Id: SampleTable
      Permissions:
      - Read
    Metadata:
      SamResourceId: SampleConnector
  SampleFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://sam-773427694428-eu-west-1/b2de06efb355ff47d2a3bf88480b2d03
      Handler: index.lambda_handler
      Runtime: python3.10
      Architectures:
      - arm64
      Layers:
      - Ref: SampleLayer
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /
            Method: get
            RestApiId:
              Ref: SampleApi
      Tags:
        LeaveTag: This should stay
    Connectors:
      MyDDBConnector:
        Properties:
          Destination:
            Id: SampleTable
          Permissions:
          - Read
          - Write
    Metadata:
      SamResourceId: SampleFunction
  SampleInlineFunction:
    Type: AWS::Serverless::Function
    Metadata:
      InlineSAMFunction: true
      LeaveMetadata: This should stay
      LeaveMetadata2: This should stay
      SamResourceId: SampleInlineFunction
    Properties:
      CodeUri: s3://sam-773427694428-eu-west-1/b2de06efb355ff47d2a3bf88480b2d03
      Handler: index.lambda_handler
      Runtime: python3.10
      Architectures:
      - arm64
      Layers:
      - Ref: SampleLayer
  # SampleHttpApi:
  #   Type: AWS::Serverless::HttpApi
  #   Properties:
  #     StageName:
  #       Ref: APIStageName
  #     AccessLogSettings:
  #       DestinationArn:
  #         Fn::Sub: ${SampleHttpApiLogGroup.Arn}
  #       Format: $context.requestId
  #     DefaultRouteSettings:
  #       ThrottlingBurstLimit: 200
  #     RouteSettings:
  #       GET /path:
  #         ThrottlingBurstLimit: 500
  #     StageVariables:
  #       StageVar: Value
  #     FailOnWarnings: true
  #   Metadata:
  #     SamResourceId: SampleHttpApi
  # SampleHttpApiLogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Metadata:
  #     SamResourceId: SampleHttpApiLogGroup
  SampleLayer:
    Type: AWS::Serverless::LayerVersion
    DeletionPolicy: Delete
    Properties:
      LayerName: SampleLayer
      ContentUri: s3://sam-773427694428-eu-west-1/81a135cc28f797dfb00c07dc70670789
      CompatibleRuntimes:
      - python3.10
    Metadata:
      BuildMethod: python3.10
      SamResourceId: SampleLayer
  SampleTable:
    Type: AWS::Serverless::SimpleTable
    DeletionPolicy: Delete
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-SampleTable
    Metadata:
      SamResourceId: SampleTable
